/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Statements } from "./Statements";

export { Statements__factory } from "./factories/Statements__factory";
